---
title: "Final Project"
author: "Karim and Mustafa"
date: "10/27/2022"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("Hmisc")
# install.packages("pastecs")
# install.packages("ggplot2")
# install.packages("Hmisc")
# install.packages("fastDummies")
# install.packages("lmtest")
```


```{r}
library(ggplot2)
library(psych)
library(corrplot)
library(caret)
library(glmnet)
library(leaps)
library(reshape2)
library(gridExtra)
library(fastDummies)
library(lmtest)
```




```{r}
# reading file
caravan_insurance = readr::read_csv("caravan-insurance-challenge.csv")
```


# Step 1 Data Visulation and exploration

```{r}
dimension = dim(caravan_insurance)
# total number of observations are 9822
# total number of variables are 87 

totalRows = dimension[1]

str(caravan_insurance)
# data type of 86 variables is number and 1 variable is char, our target variable is number of policies bought remaining variables are categorical numeric.

head(caravan_insurance)
# explore top 5 rows
```

# Descriptive analysis
```{r}
# summary of main data set
stat.desc(caravan_insurance)
summary(caravan_insurance)

# missing values in main data set
paste0("Total missing values:", sum(is.na(caravan_insurance)))

# summary of training data set
stat.desc(caravan_insurance_train)

# checking missing values in training data set
paste0("Total missing values in training:", sum(is.na(caravan_insurance_train)))


# summary of test data set
stat.desc(caravan_insurance_test)

# checking missing values in training data set
paste0("Total missing values in test:", sum(is.na(caravan_insurance_test)))

```


# Plot graphs
```{r}
library(ggplot2)
library(plyr)



unInsuredRows = caravan_insurance[caravan_insurance$CARAVAN == 0,]
insuredRows = caravan_insurance[caravan_insurance$CARAVAN == 1,]
df = 

peopleNotInsuredWithCaravan  <- nrow(unInsuredRows);
peopleInsuredWithCaravan = nrow(insuredRows);


ratioOfPeopleWhoDontBought = peopleNotInsuredWithCaravan/totalRows * 100
ratioOfPeopleWhoBought = peopleInsuredWithCaravan/totalRows * 100
# 5.96% who bought insurance vs 94% who didn't buy the insurance, by statistics it looks like company is in loss people are not interested in buying they have to something to improve.

dat <- data.frame(
  policy_status = factor(c("Not Insured","Insured"), levels=c("Not Insured","Insured")),
  Count = c( peopleNotInsuredWithCaravan , peopleInsuredWithCaravan)
)

ggplot(data=dat, aes(x=policy_status, y=Count, fill=policy_status)) +
  geom_bar(colour="red", stat="identity")

```

# Now we will see what type of customers bought the insurance?

```{r}
hist(insuredRows$MOSHOOFD, main="Insured Customer type",
     xlab = "Insured Customer type", col="blue")

# interesting insights customer with type Successful hedonists bought more policy as compare to an others, also customer with Average Family didn't buy any insurance. so company has to offer more benefits to average familes so they can buy it

hist(unInsuredRows$MOSHOOFD, main="Un Insured Customer type",
     xlab = "Un Insured Customer type", col="blue")
# Family with grown ups has higher number as they didn't buy insurance at all. it might be possible they have children and other expensive so they can't afford it?
```


```{r}
hist(caravan_insurance$MOSTYPE, main="Customer Subtype",
     xlab = "Customer Subtype", col="blue")
hist(caravan_insurance$MAANTHUI, main="Number of houses",
     xlab = "Number of houses", col="blue")
hist(caravan_insurance$MOSHOOFD, main="Customer Main type",
     xlab = "Customer Main type", col="green")
hist(caravan_insurance$MGEMOMV, main="Average Household size",
     xlab = "Average Household size", col="green")
hist(caravan_insurance$MGEMLEEF, main="Average Age",
     xlab = "Average Age", col="green")

hist(caravan_insurance$MINKM30, main="low income",
     xlab = "low income", col="green")

# boxplot(caravan_insurance$MINKM30, xlab = "MINKM30", ylab = "MINKM30 Size", main ="MINKM30")

# boxplot(caravan_insurance$MGEMOMV, xlab = "Household", ylab = "Household Size", main ="Household")

```


# corelation analysis.

```{r}
set = caravan_insurance
set$ORIGIN = NULL
rcorr(as.matrix(set))
#P1 = MOSTYPE (Customer Subtype) -0.06
# customer subtype has weak corelation with response variable CARVAN so we can use for further analysis

#P3 = MGEMOMV (Avg size household) 0.05
#P4 = MGEMLEEF (Average age) 0.00
#P5 = MOSHOOFD (Customer Main Type) -0.06
#P2 = MAANTHUI (Number of houses)  0.00
```

# Dummies conversion
# Number of Houses
```{r}
table(caravan_insurance$MAANTHUI)

caravan_insurance$MAANTHUI = replace(caravan_insurance$MAANTHUI, caravan_insurance$MAANTHUI==3, 2)
caravan_insurance$hasOneHouse = ifelse(caravan_insurance$MAANTHUI ==1, 1, 0)
caravan_insurance$hasTwoHouses = ifelse(caravan_insurance$MAANTHUI ==2, 1, 0)
caravan_insurance$moreThan4Houses = ifelse(caravan_insurance$MAANTHUI > 4, 1, 0)

# by looking frequencies of houses we categorized houses into dummies.
```

# Grouping sub customer to meanful customer type.
```{r}
caravan_insurance$averageFamily = ifelse(caravan_insurance$MOSTYPE %in% c(12,11,9,10,13), 1, 0)
caravan_insurance$loners = ifelse(caravan_insurance$MOSTYPE %in% c(17,15,18,16,19), 1, 0)
caravan_insurance$conservativeFamilies = ifelse(caravan_insurance$MOSTYPE %in% c(39,38), 1, 0)
caravan_insurance$crusingSeniors = ifelse(caravan_insurance$MOSTYPE %in% c(26,25,28,27), 1, 0)
caravan_insurance$drivenGrowers = ifelse(caravan_insurance$MOSTYPE %in% c(6,7,8), 1, 0)
caravan_insurance$grownups = ifelse(caravan_insurance$MOSTYPE %in% c(33,34,35,36,37), 1, 0)
caravan_insurance$framers = ifelse(caravan_insurance$MOSTYPE %in% c(40,41), 1, 0)
caravan_insurance$livingWell = ifelse(caravan_insurance$MOSTYPE %in% c(20,21,22,23,24), 1, 0)
caravan_insurance$retired = ifelse(caravan_insurance$MOSTYPE %in% c(29,30,31,32), 1, 0)
caravan_insurance$successful = ifelse(caravan_insurance$MOSTYPE %in% c(1,2,3,4,5), 1, 0)


dat <- data.frame(
  Categorized_Customers = factor(c("averageFamily", "loners", "conservativeFamilies", "crusingSeniors", "drivenGrowers", "grownups", "framers", "livingWell", "retired", "successful"), levels=c("averageFamily", "loners", "conservativeFamilies", "crusingSeniors", "drivenGrowers", "grownups", "framers", "livingWell", "retired", "successful")),
  Count = c( sum(caravan_insurance$averageFamily), sum(caravan_insurance$loners), sum(caravan_insurance$conservativeFamilies), sum(caravan_insurance$crusingSeniors), sum(caravan_insurance$drivenGrowers), sum(caravan_insurance$grownups), sum(caravan_insurance$framers), sum(caravan_insurance$livingWell), sum(caravan_insurance$retired), sum(caravan_insurance$successful) )
)

ggplot(data=dat, aes(x=Categorized_Customers, y=Count, fill=Categorized_Customers)) +
  geom_bar(colour="red", stat="identity")

```


# Income
```{r}
car_policies <- sum(caravan_insurance$PPERSAUT != 0)
car_policies
```


```{r}
# MOSTYPE : customer subtype
# MFWEKIND: Household with children
# MOPLLAAG: Lower level education
# MHHUUR :  Rented house
# MHKOOP :  Home owners
# MINKM30:  Income < 30.000 low income
# MINK7512: Income 75-122.000 high income
# MKOOPKLA: Purchasing power class
# PPERSAUT: Contribution car policies
# CARAVAN:  Number of mobile home policies 0 - 1

names(caravan_insurance)[names(caravan_insurance) == "MFWEKIND"] = "house_hold_child"
names(caravan_insurance)[names(caravan_insurance) == "MOPLLAAG"] = "lower_level_educ"
names(caravan_insurance)[names(caravan_insurance) == "MHHUUR"] = "rented_house"
names(caravan_insurance)[names(caravan_insurance) == "MHKOOP"] = "home_owners"
names(caravan_insurance)[names(caravan_insurance) == "MINKM30"] = "income_less_than_30k"
names(caravan_insurance)[names(caravan_insurance) == "MINK7512"] = "income_greater_than_75k_and_less_122k"
names(caravan_insurance)[names(caravan_insurance) == "MKOOPKLA"] = "purchasing_power"
names(caravan_insurance)[names(caravan_insurance) == "PPERSAUT"] = "contribution_car_policies"

updated_data = data.frame(subset(caravan_insurance, select = c("ORIGIN", "drivenGrowers", "averageFamily", "conservativeFamilies", "hasOneHouse", "hasTwoHouses", "moreThan4Houses", "house_hold_child", "lower_level_educ", "rented_house", "home_owners", "income_less_than_30k", "income_greater_than_75k_and_less_122k", "purchasing_power", "contribution_car_policies", "CARAVAN")))
updated_data

```


# Partition data

```{r}
# training data
caravan_insurance_train = (updated_data[updated_data$ORIGIN == "train",])

#testing data
caravan_insurance_test = (updated_data[updated_data$ORIGIN == "test",])
```

```{r}
dim(caravan_insurance_train)
dim(caravan_insurance_test)
```

```{r}
caravan_insurance_train = (caravan_insurance_train[,-1])
caravan_insurance_test = (caravan_insurance_test[,-1])
```

```{r}
head(caravan_insurance_train)
head(caravan_insurance_test)
```

```{r}
xtabs(~contribution_car_policies + CARAVAN, data = caravan_insurance_train)
```


```{r}
# Logistic train fit
logisticTrainingFit <- glm(CARAVAN ~ drivenGrowers + hasOneHouse + income_less_than_30k, family=binomial(link='logit'), data = caravan_insurance_train)
coeftest(logisticTrainingFit, type = "HC1")
anova(logisticTrainingFit, test="Chisq")
```

```{r}
LOutPredicted <- predict(logisticTrainingFit, type = "response")
LOutPredictedClass <- ifelse(LOutPredicted>0.5, 1, 0)
misClasificError <- mean(LOutPredictedClass != caravan_insurance_train$CARAVAN)
print(paste('Accuracy',1-misClasificError))
```


